/**
 * Local knowledge base for Ollama mode.
 *
 * Replaces OpenAI's hosted file_search/vector stores with a small local RAG path:
 * - Markdown source documents live in <KNOWLEDGE_BASE_DIR>/docs/
 * - Chunks + embeddings are persisted in <KNOWLEDGE_BASE_DIR>/index.json
 * - Embeddings are generated by a local Ollama embedding model via /v1/embeddings
 * - Retrieval is cosine similarity over the persisted chunk embeddings
 *
 * The corpus is small (how-to articles and troubleshooting notes written by the
 * bot itself via update_knowledge), so a flat JSON index is deliberately preferred
 * over a dedicated vector database.
 */

import fsp from "node:fs/promises";
import path from "node:path";
import { getOllamaConfig } from "../config/providers.js";

/** Default location for local knowledge base data */
const DEFAULT_KB_DIR = "data/knowledge";

/** Chunking parameters (characters) */
const CHUNK_SIZE = 1200;
const CHUNK_OVERLAP = 200;

/** Retrieval defaults */
const DEFAULT_TOP_K = 5;
const MAX_TOP_K = 10;

/** Embedding requests are batched to keep payloads small */
const EMBEDDING_BATCH_SIZE = 16;

/**
 * Function tool definition for local knowledge base search.
 */
export const SEARCH_KNOWLEDGE_TOOL = {
	type: "function",
	name: "search_knowledge_base",
	description:
		"Search the IT knowledge base of past learnings, solutions, and how-to articles. Returns the most relevant excerpts with their source document so you can cite them. Use it before answering questions about known procedures, past incidents, or documented configurations.",
	parameters: {
		type: "object",
		properties: {
			query: {
				type: "string",
				description: "What to look for, phrased as a natural-language question or keywords.",
			},
			topK: {
				type: "number",
				description: `Number of excerpts to return (1-${MAX_TOP_K}, default ${DEFAULT_TOP_K}).`,
			},
		},
		required: ["query"],
		additionalProperties: false,
	},
};

/**
 * Get the knowledge base data directory.
 *
 * @returns {string} Absolute or cwd-relative directory path
 */
export function getKnowledgeBaseDir() {
	return process.env.KNOWLEDGE_BASE_DIR || DEFAULT_KB_DIR;
}

/**
 * Split a markdown document into overlapping chunks, keeping section headings
 * as metadata so retrieved excerpts can be cited.
 *
 * @param {string} text - Document text
 * @param {Object} [options]
 * @param {number} [options.chunkSize] - Target chunk size in characters
 * @param {number} [options.overlap] - Overlap between consecutive chunks
 * @returns {Array<{text: string, section: string|null}>}
 */
export function chunkDocument(text, { chunkSize = CHUNK_SIZE, overlap = CHUNK_OVERLAP } = {}) {
	const clean = String(text || "").trim();
	if (!clean) return [];

	// Split into sections on markdown headings (levels 1-3)
	const lines = clean.split("\n");
	const sections = [];
	let current = { section: null, lines: [] };

	for (const line of lines) {
		const heading = line.match(/^#{1,3}\s+(.+)$/);
		if (heading) {
			if (current.lines.join("\n").trim()) sections.push(current);
			current = { section: heading[1].trim(), lines: [line] };
		} else {
			current.lines.push(line);
		}
	}
	if (current.lines.join("\n").trim()) sections.push(current);

	// Window each section into chunks
	const chunks = [];
	for (const { section, lines: sectionLines } of sections) {
		const sectionText = sectionLines.join("\n").trim();
		if (!sectionText) continue;

		if (sectionText.length <= chunkSize) {
			chunks.push({ text: sectionText, section });
			continue;
		}

		let start = 0;
		while (start < sectionText.length) {
			let end = Math.min(start + chunkSize, sectionText.length);
			// Prefer to break on a paragraph or line boundary
			if (end < sectionText.length) {
				const paragraphBreak = sectionText.lastIndexOf("\n\n", end);
				const lineBreak = sectionText.lastIndexOf("\n", end);
				const breakAt = paragraphBreak > start + chunkSize / 2 ? paragraphBreak : lineBreak;
				if (breakAt > start + chunkSize / 2) end = breakAt;
			}
			chunks.push({ text: sectionText.slice(start, end).trim(), section });
			if (end >= sectionText.length) break;
			start = Math.max(end - overlap, start + 1);
		}
	}

	return chunks.filter((c) => c.text);
}

/**
 * Cosine similarity between two equal-length vectors.
 *
 * @param {number[]} a
 * @param {number[]} b
 * @returns {number} Similarity in [-1, 1], 0 for degenerate inputs
 */
export function cosineSimilarity(a, b) {
	if (!Array.isArray(a) || !Array.isArray(b) || a.length !== b.length || a.length === 0) {
		return 0;
	}

	let dot = 0;
	let normA = 0;
	let normB = 0;

	for (let i = 0; i < a.length; i++) {
		dot += a[i] * b[i];
		normA += a[i] * a[i];
		normB += b[i] * b[i];
	}

	const denominator = Math.sqrt(normA) * Math.sqrt(normB);
	return denominator > 0 ? dot / denominator : 0;
}

/**
 * Task prefixes required by the embedding model for good retrieval quality.
 * nomic-embed-text is trained with asymmetric search_query/search_document
 * prefixes and degrades noticeably without them; mxbai-embed-large uses a
 * query-side instruction only; most other models (bge-m3, ...) need none.
 * Override with OLLAMA_EMBEDDING_QUERY_PREFIX / OLLAMA_EMBEDDING_DOCUMENT_PREFIX.
 *
 * @param {string} [model] - Embedding model name (defaults to the configured one)
 * @returns {{query: string, document: string}}
 */
export function getEmbeddingPrefixes(model = getOllamaConfig().embeddingModel) {
	const queryOverride = process.env.OLLAMA_EMBEDDING_QUERY_PREFIX;
	const documentOverride = process.env.OLLAMA_EMBEDDING_DOCUMENT_PREFIX;
	if (queryOverride !== undefined || documentOverride !== undefined) {
		return { query: queryOverride || "", document: documentOverride || "" };
	}

	if (/nomic-embed/i.test(model)) {
		return { query: "search_query: ", document: "search_document: " };
	}
	if (/mxbai-embed/i.test(model)) {
		return {
			query: "Represent this sentence for searching relevant passages: ",
			document: "",
		};
	}
	return { query: "", document: "" };
}

/**
 * Generate embeddings for a batch of texts via the local Ollama /v1/embeddings endpoint.
 *
 * @param {string[]} texts - Texts to embed
 * @param {Object} [logger] - Logger instance
 * @param {string} [taskPrefix] - Model-specific task prefix (see getEmbeddingPrefixes)
 * @returns {Promise<number[][]>} One embedding per input text
 */
export async function embedTexts(texts, logger, taskPrefix = "") {
	const { baseUrl, apiKey, embeddingModel } = getOllamaConfig();
	const prefixedTexts = taskPrefix ? texts.map((text) => taskPrefix + text) : texts;
	const embeddings = [];

	for (let offset = 0; offset < prefixedTexts.length; offset += EMBEDDING_BATCH_SIZE) {
		const batch = prefixedTexts.slice(offset, offset + EMBEDDING_BATCH_SIZE);

		let response;
		try {
			response = await fetch(`${baseUrl}/embeddings`, {
				method: "POST",
				headers: {
					Authorization: `Bearer ${apiKey}`,
					"Content-Type": "application/json",
				},
				body: JSON.stringify({ model: embeddingModel, input: batch }),
				signal: AbortSignal.timeout(60000),
			});
		} catch (e) {
			throw new Error(`Embedding service unreachable at ${baseUrl}: ${e?.message || e}`);
		}

		if (!response.ok) {
			const errorText = await response.text().catch(() => "");
			throw new Error(
				`Embedding request failed (HTTP ${response.status}). Is the embedding model pulled? Try: ollama pull ${embeddingModel}. ${errorText.slice(0, 200)}`
			);
		}

		const body = await response.json();
		const data = Array.isArray(body?.data) ? body.data : [];
		if (data.length !== batch.length) {
			throw new Error(
				`Embedding service returned ${data.length} vectors for ${batch.length} inputs`
			);
		}

		for (const item of data) {
			if (!Array.isArray(item?.embedding)) {
				throw new Error("Embedding service returned an invalid vector");
			}
			embeddings.push(item.embedding);
		}

		logger?.debug?.(`[KB] Embedded batch of ${batch.length} texts`);
	}

	return embeddings;
}

function slugify(title) {
	return (
		String(title || "knowledge-entry")
			.toLowerCase()
			.replace(/[^a-z0-9]+/g, "-")
			.replace(/^-+|-+$/g, "")
			.slice(0, 80) || "knowledge-entry"
	);
}

/**
 * Create a local knowledge base instance.
 *
 * @param {Object} [options]
 * @param {string} [options.dir] - Data directory (defaults to KNOWLEDGE_BASE_DIR)
 * @param {Object} [options.logger] - Logger instance
 * @returns {Object} Knowledge base with isAvailable, search, addDocument, reindex
 */
export function createLocalKnowledgeBase({ dir = getKnowledgeBaseDir(), logger } = {}) {
	const docsDir = path.join(dir, "docs");
	const indexPath = path.join(dir, "index.json");
	let cachedIndex = null;

	async function loadIndex() {
		if (cachedIndex) return cachedIndex;
		try {
			const raw = await fsp.readFile(indexPath, "utf8");
			const parsed = JSON.parse(raw);
			if (parsed && Array.isArray(parsed.chunks)) {
				cachedIndex = parsed;
				return cachedIndex;
			}
		} catch {
			// Missing or invalid index — knowledge base is empty/unavailable
		}
		return null;
	}

	async function saveIndex(index) {
		await fsp.mkdir(dir, { recursive: true });
		await fsp.writeFile(indexPath, JSON.stringify(index), "utf8");
		cachedIndex = index;
	}

	async function isAvailable() {
		const index = await loadIndex();
		return Boolean(index && index.chunks.length > 0);
	}

	/**
	 * Search the knowledge base.
	 *
	 * @param {string} query - Natural-language query
	 * @param {number} [topK] - Number of excerpts to return
	 * @returns {Promise<Object>} {ok, results: [{title, source, section, excerpt, score}]}
	 */
	async function search(query, topK = DEFAULT_TOP_K) {
		const cleanQuery = String(query || "").trim();
		if (!cleanQuery) {
			return { ok: false, error: "Missing required parameter: query" };
		}

		const index = await loadIndex();
		if (!index || index.chunks.length === 0) {
			return {
				ok: false,
				error:
					"Knowledge base is empty or not indexed. Run `npm run kb:index` (or `npm run kb:export` first to migrate documents from OpenAI).",
			};
		}

		const { embeddingModel } = getOllamaConfig();
		if (index.model && index.model !== embeddingModel) {
			return {
				ok: false,
				error: `Knowledge base index was built with embedding model "${index.model}" but "${embeddingModel}" is configured. Rebuild it with: npm run kb:index`,
			};
		}

		const prefixes = getEmbeddingPrefixes(embeddingModel);
		if ((index.documentPrefix || "") !== prefixes.document) {
			return {
				ok: false,
				error:
					"Knowledge base index was built with a different embedding task prefix. Rebuild it with: npm run kb:index",
			};
		}

		let queryEmbedding;
		try {
			[queryEmbedding] = await embedTexts([cleanQuery], logger, prefixes.query);
		} catch (e) {
			logger?.error?.("[KB] Query embedding failed", { error: String(e) });
			return { ok: false, error: `Knowledge base unavailable: ${e?.message || e}` };
		}

		const limit = Math.min(Math.max(Math.floor(topK) || DEFAULT_TOP_K, 1), MAX_TOP_K);

		const scored = index.chunks
			.map((chunk) => ({ chunk, score: cosineSimilarity(queryEmbedding, chunk.embedding) }))
			.sort((a, b) => b.score - a.score)
			.slice(0, limit);

		return {
			ok: true,
			query: cleanQuery,
			results: scored.map(({ chunk, score }) => ({
				title: chunk.title,
				source: chunk.source,
				section: chunk.section || null,
				excerpt: chunk.text,
				score: Number(score.toFixed(4)),
			})),
		};
	}

	/**
	 * Add (or logically replace) a knowledge document: write the markdown source,
	 * embed its chunks, and persist them in the index.
	 *
	 * @param {Object} params
	 * @param {string} params.title - Document title
	 * @param {string} params.content - Markdown content
	 * @param {string} [params.replaceDocId] - Existing docId to replace
	 * @returns {Promise<Object>} {ok, docId, file} or {ok: false, error}
	 */
	async function addDocument({ title, content, replaceDocId }) {
		const cleanTitle = String(title || "knowledge-entry").trim();
		const cleanContent = String(content || "").trim();
		if (!cleanContent) {
			return { ok: false, error: "Content is required" };
		}

		const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
		const docId = `${slugify(cleanTitle)}-${timestamp}`;
		const fileName = `${docId}.md`;
		const fullContent = `# ${cleanTitle}\n\nCreated: ${new Date().toISOString()}\n\n${cleanContent}`;

		const pieces = chunkDocument(fullContent);
		if (pieces.length === 0) {
			return { ok: false, error: "Document produced no indexable content" };
		}

		const { embeddingModel } = getOllamaConfig();
		const documentPrefix = getEmbeddingPrefixes(embeddingModel).document;
		const index = (await loadIndex()) || { model: embeddingModel, documentPrefix, chunks: [] };
		index.model = index.model || embeddingModel;
		if (index.documentPrefix === undefined) index.documentPrefix = documentPrefix;

		// Never mix vectors from different embedding configurations in one index
		if (index.model !== embeddingModel || index.documentPrefix !== documentPrefix) {
			return {
				ok: false,
				error: `Knowledge base index was built with embedding model "${index.model}" but "${embeddingModel}" is configured. Rebuild it with: npm run kb:index`,
			};
		}

		let embeddings;
		try {
			embeddings = await embedTexts(
				pieces.map((p) => p.text),
				logger,
				documentPrefix
			);
		} catch (e) {
			logger?.error?.("[KB] Document embedding failed", { error: String(e) });
			return { ok: false, error: `Cannot index knowledge: ${e?.message || e}` };
		}

		await fsp.mkdir(docsDir, { recursive: true });
		await fsp.writeFile(path.join(docsDir, fileName), fullContent, "utf8");

		if (replaceDocId) {
			index.chunks = index.chunks.filter((chunk) => chunk.docId !== replaceDocId);
		}

		for (let i = 0; i < pieces.length; i++) {
			index.chunks.push({
				id: `${docId}#${i}`,
				docId,
				title: cleanTitle,
				source: `docs/${fileName}`,
				section: pieces[i].section,
				text: pieces[i].text,
				embedding: embeddings[i],
			});
		}

		await saveIndex(index);
		logger?.info?.(`[KB] Indexed document "${cleanTitle}" (${pieces.length} chunks)`);

		return { ok: true, docId, file: fileName, chunks: pieces.length };
	}

	/**
	 * Incrementally (re-)index a single document from docs/ into the existing
	 * index, replacing any previous chunks for that document. Avoids a full
	 * rebuild after editing one file.
	 *
	 * @param {string} fileName - File name inside docs/ (path components ignored)
	 * @returns {Promise<Object>} {ok, docId, chunks} or {ok: false, error}
	 */
	async function indexFile(fileName) {
		const cleanName = path.basename(String(fileName || "").trim());
		if (!cleanName) {
			return { ok: false, error: "Missing file name" };
		}

		let content;
		try {
			content = await fsp.readFile(path.join(docsDir, cleanName), "utf8");
		} catch {
			return { ok: false, error: `Document not found: ${path.join(docsDir, cleanName)}` };
		}

		const { embeddingModel } = getOllamaConfig();
		const documentPrefix = getEmbeddingPrefixes(embeddingModel).document;
		const index = (await loadIndex()) || { model: embeddingModel, documentPrefix, chunks: [] };
		index.model = index.model || embeddingModel;
		if (index.documentPrefix === undefined) index.documentPrefix = documentPrefix;

		// Never mix vectors from different embedding configurations in one index
		if (index.model !== embeddingModel || index.documentPrefix !== documentPrefix) {
			return {
				ok: false,
				error: `Knowledge base index was built with embedding model "${index.model}" but "${embeddingModel}" is configured. Rebuild it with: npm run kb:index`,
			};
		}

		const titleMatch = content.match(/^#\s+(.+)$/m);
		const title = titleMatch ? titleMatch[1].trim() : cleanName.replace(/\.[^.]+$/, "");
		const docId = cleanName.replace(/\.[^.]+$/, "");

		const pieces = chunkDocument(content);
		if (pieces.length === 0) {
			return { ok: false, error: `Document produced no indexable content: ${cleanName}` };
		}

		let embeddings;
		try {
			embeddings = await embedTexts(
				pieces.map((p) => p.text),
				logger,
				documentPrefix
			);
		} catch (e) {
			return { ok: false, error: `Cannot index ${cleanName}: ${e?.message || e}` };
		}

		index.chunks = index.chunks.filter((chunk) => chunk.docId !== docId);
		for (let i = 0; i < pieces.length; i++) {
			index.chunks.push({
				id: `${docId}#${i}`,
				docId,
				title,
				source: `docs/${cleanName}`,
				section: pieces[i].section,
				text: pieces[i].text,
				embedding: embeddings[i],
			});
		}

		await saveIndex(index);
		logger?.info?.(`[KB] Re-indexed ${cleanName} (${pieces.length} chunks)`);

		return { ok: true, docId, chunks: pieces.length };
	}

	/**
	 * Rebuild the whole index from the markdown documents in docs/.
	 *
	 * @returns {Promise<Object>} {ok, documents, chunks} or {ok: false, error}
	 */
	async function reindex() {
		let entries;
		try {
			entries = await fsp.readdir(docsDir);
		} catch {
			return { ok: false, error: `No documents directory found at ${docsDir}` };
		}

		const markdownFiles = entries.filter((f) => /\.(md|markdown|txt)$/i.test(f)).sort();
		if (markdownFiles.length === 0) {
			return { ok: false, error: `No documents found in ${docsDir}` };
		}

		const { embeddingModel } = getOllamaConfig();
		const documentPrefix = getEmbeddingPrefixes(embeddingModel).document;
		const index = { model: embeddingModel, documentPrefix, chunks: [] };

		for (const fileName of markdownFiles) {
			const content = await fsp.readFile(path.join(docsDir, fileName), "utf8");
			const titleMatch = content.match(/^#\s+(.+)$/m);
			const title = titleMatch ? titleMatch[1].trim() : fileName.replace(/\.[^.]+$/, "");
			const docId = fileName.replace(/\.[^.]+$/, "");

			const pieces = chunkDocument(content);
			if (pieces.length === 0) continue;

			const embeddings = await embedTexts(
				pieces.map((p) => p.text),
				logger,
				documentPrefix
			);

			for (let i = 0; i < pieces.length; i++) {
				index.chunks.push({
					id: `${docId}#${i}`,
					docId,
					title,
					source: `docs/${fileName}`,
					section: pieces[i].section,
					text: pieces[i].text,
					embedding: embeddings[i],
				});
			}

			logger?.info?.(`[KB] Indexed ${fileName} (${pieces.length} chunks)`);
		}

		await saveIndex(index);
		return { ok: true, documents: markdownFiles.length, chunks: index.chunks.length };
	}

	return { isAvailable, search, addDocument, indexFile, reindex, dir, docsDir, indexPath };
}
